name: QuizMaster Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Matches your SDK constraint
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze # Catches those 'ek' typos or unused imports

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi -t main.dart

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
